colormode: RGB
inference:
  normalize_images: true
train:
  affine:
    p: 0.5
    rotation: 30
    scaling: [0.5, 1.25]
    translation: 0
  covering: false
  crop_sampling:
    width: 400
    height: 400
    max_shift: 0.1
    method: hybrid
  gaussian_noise: 12.75
  hist_eq: false
  motion_blur: false
  normalize_images: true
