type: HeatmapHead
predictor:
  type: HeatmapPredictor
  location_refinement: false
target_generator:
  type: HeatmapPlateauGenerator
  num_heatmaps: "num_individuals"
  pos_dist_thresh: 17
  heatmap_mode: INDIVIDUAL
  generate_locref: false
criterion:
  heatmap:
    type: WeightedBCECriterion
    weight: 1.0
heatmap_config:
  channels:
  - "backbone_output_channels"
  - "num_individuals"
  kernel_size:
  - 3
  strides:
  - 2
